const products = [
    {
        _id: '001',
        name: "Assassin's creed odyssey",
        category: 'XBOX',
        image: '../images/p1.jpg',
        price: 29.00,
        brand: "UBSOFT",
        countInStock: 10,
    },
    {
        _id: '002',
        name: "Cyberpunk",
        category: 'PC',
        image: "../images/p2.jpg",
        price: 99.95,
        brand: "CD PROJEKT RED",
        countInStock: 21,
    },        
    {
        _id: '003',
        name: "Tom Clancy's The Division 2",
        category: 'PC',
        image: "../images/p3.jpg",
        price: 19.98,
        brand: "UBSOFT",
        countInStock: 100,
    },        
    {
        _id: '004',
        name: "World of Warcraft: Battle for Azeroth",
        category: 'PC',
        image: "../images/p4.jpg",
        price: 39.00,
        brand: "BLIZZARD",
        countInStock: 30,
    },        
    {
        _id: '005',
        name: "Sekiro: Shadows Die Twice",
        category: 'PC',
        image: "../images/p5.jpg",
        price: 49.00,
        brand: "FROMSOFTWARE",
        countInStock: 60,
    },
    {
        _id: '006',
        name: "Metro Exodus",
        category: 'PC',
        image: "../images/p6.jpg",
        price: 29.00,
        brand: "DEEP SILVER",
        countInStock: 200,
    },
]

exports.products = products;